### ISSUE TITLE
Training time

### ISSUE THREAD

**Issue by fabge** [earthspecies/open_collaboration_on_audio_classification#1]
Thank you for taking part in this years course again and engaging with the community 🙂 

When I was trying to train the `cnn_learner`, a single epoch takes ~20 minutes to train.
Did you use an extremely powerful GPU or am I doing something wrong because it seems to have taken seconds in the provided notebook?
Currently using Google Colab with a GPU.

**Comment by radekosmulski** [comment]
Thank you very much for your kind words 🙂 I feel very privileged to continue to be part of this community 😊

I am using a 1080ti, but even between something like a v100 and k80 (very old server card by today's standard) the difference shouldn't be even close to being this big. It think you should probably check if the GPU is being utilized. I am not sure how to do it on colab, locally I would just run `nvidia-smi -l` or `nvidia-smi dmon`.

If there is a way of opening at terminal for the machine you are training on (maybe via jupyter notebook?) you could probably run one of these commands and see what's going on. Maybe there is also something else one could do specific to colab. Quite convinced your runtime either doesn't have a GPU attached or for some reason your model is not using it for training.

I am quite sure there is also a more elegant way to do this using something in fastai (maybe try checking what `default_device()` returns?) but there is also this you could try 

```
next(model.parameters()).is_cuda # returns a boolean
```

You might need to do this after training for at least a little bit as IIRC fastai might only be putting the model on GPU via a callback at training start (don't quote me on that though 🙂)

**Comment by AdPostma** [comment]
The problem in Colab is the use of the librosa.load(). This takes more than 20 min to read in all the wav files. I also tried torchadio.load() which only takes 1.1 sec to read them all. I have notyet  figured  out a way to load this data into the dataloader.

**Comment by radekosmulski** [comment]
Oh cool, yes, this could be it, great observation @AdPostma 🙂 Can you please try training with fewer workers?

![image](https://user-images.githubusercontent.com/2444926/77468246-9a440280-6e0d-11ea-823c-ee2f0eef1aa0.png)

librosa has this behavior where it already spawns multiple processes or threads to complete certain tasks... not sure what exactly it does for downsampling, but here for sure 12 is too high, IIRC colab has two vcpus

**Comment by radekosmulski** [comment]
seems `librosa.load` is super slow not even in  the dataloader, but just iterating over the paths and reading them in...

**Comment by radekosmulski** [comment]
I played around with this some more, switched to `torchaudio`. With `torchaudio` I am seeing the same situation, meaning the processing of audio takes forever (~20 mins per epoch)
![image](https://user-images.githubusercontent.com/2444926/77476561-15f87c00-6e1b-11ea-9aff-c76da95be5f2.png)

The culprit is the downsampling step for some of the files (some are at higher kHz than most). 

That is an extreme bummer. 18 seconds on my local machine with just a Ryzen6 vs 20 min on colab!

The solution here would be uploading already downsampled data. Already late around here so I'll probably get around to doing this tomorrow 🙂

**Comment by AdPostma** [comment]
Took exactly the same route with torchaudio.transforms.Resample() and with the same result.
Looking forward to your results of tomorrow.

**Comment by fabge** [comment]
Awesome, thanks! 🙂

**Comment by radekosmulski** [comment]
everything should be running on colab now 🙂

**Comment by fabge** [comment]
Colab training time unfortunately didn't improve...
I used the new notebook by using the badge link. Running the notebook still takes a long time, despite using a gpu (I checked 🙂)
![image](https://user-images.githubusercontent.com/21140791/77539674-0f611780-6ea2-11ea-871d-4f60fac21a4d.png)

**Comment by fabge** [comment]
Using the Introduction.ipynb notebook works by training for about a minute, though!
![image](https://user-images.githubusercontent.com/21140791/77540569-98c51980-6ea3-11ea-94f4-6a14ae06f613.png)

**Comment by radekosmulski** [comment]
thank you for noticing this and sorry for the trouble 🙂 everything should be fixed now - the template notebook was still using the `URLs.MACAQUES` url, this should be fixed now

**Comment by fabge** [comment]
Ha, I found it out the minute you posted our answer.
No worries, thank **you** for putting in the effort! 🙂
