### ISSUE TITLE
This repo should be named for the species it works with and linked from the Library page

### ISSUE THREAD

**Issue by aza** [earthspecies/open_collaboration_on_audio_classification#8]

**Comment by radekosmulski** [comment]
Here are the changes:

![image](https://user-images.githubusercontent.com/2444926/85683511-95714200-b6cd-11ea-9d60-3fea1a78e6e2.png)

![image](https://user-images.githubusercontent.com/2444926/85683552-a02bd700-b6cd-11ea-96cf-a625a0761c80.png)
